### ISSUE TITLE
[iOS] Add Safes, remove Safes and switching between them

### ISSUE THREAD

**Issue by DmitryBespalov** [gnosis/safe-ios#82]
- [x] There is a list of Safes (Can be empty)
- [x] User can add one or multiple Safes 
  - [x] By scanning QR code
  - ~[ ] By pasting in an address or ENS name~
  - [x] By entering an ENS name
- [x] User cannot add the same Safe twice (See [comment](https://github.com/gnosis/safe/issues/285#issuecomment-621691981) below)
- [x] Entered address is validated if it's actually a Safe or not.
  - [x] User can only proceed if it's a Safe address.
- [x] User needs to enter a (local) Safe name for that Safe
- [x] User can change the local Safe name
- [x] User can view the Safe
  - [x] ENS name
  - [x] Address
  - [x] QR code
  - [x] Identicon
- [x] User can remove a Safe from their device
- [x] User can switch between multiple Safes.
- [x] When a Safe is selected, I can see its identicon and its address on top of the screen to know it is selected.
- [x] On a cold app start, the user would see the last selected Safe.

**Comment by DmitryBespalov** [comment]
- Empty List of safes - we don't have UI for that
- Pasting the ENS name to the address is not implemented

**Comment by DmitryBespalov** [comment]
(added 12.05.2020) The order in which they were added. Active Safe is at the top. When you check another Safe in the list, the order does not change, but when you open the bottom sheet again this selected Safe is at the top. Newly added Safe becomes active Safe

**Comment by liliya-soroka** [comment]
Reopened: 
app version 0.5.0 (62) 
iphone X / 13.15.1
the active safe is not replaced to the top after switch safe page reopening
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/38d447a1-67e6-4be4-870d-3ebbaa60f2c2)

**Comment by DmitryBespalov** [comment]
@liliya-soroka I think, this epic can be closed as you have closed similar one in the safe repo, right?

**Comment by liliya-soroka** [comment]
@DmitryBespalov , I will create a separate issue ( question) to Sasha about the safes order.
I think we still need to display active safe at the top - https://app.zenhub.com/workspaces/safe-multisig---mobile-5c1b98250e13551e8aae81eb/issues/gnosis/safe-ios/427
