### ISSUE TITLE
[iOS] View Safe details and settings

### ISSUE THREAD

**Issue by DmitryBespalov** [gnosis/safe-ios#85]
User can view the following (sorted by priority):
- [x] Safe address
- [x] Contract version (0.1.0, 0.2.0, 1.0.0, 1.1.0, unknown if not known) and master copyaddress
  - [x] Check mark if it's a known one.
- [x] Required confirmations ("n our of m")
- [x] Owner addresses
- [x] ENS name (or "not set")
- [x] Advanced settings/details:
  - [x] Nonce
  - [x] Fallback handler
    - [x] "Known" if known, "Unknown" otherwise
  - [x] addresses of enabled modules
    -  ~[ ] "Unknown" or module name~
  - ~[ ] Deployment parameters (If available)~
- [x] **All addresses should have identicons and should link to Etherscan.**
