### ISSUE TITLE
[iOS] App Settings

### ISSUE THREAD

**Issue by DmitryBespalov** [gnosis/safe-ios#94]
- [x] User can see the app version.
- [x] User can see the network version (Mainnet, Rinkeby)
- [x] User can view Terms (Link to https://gnosis-safe.io/terms/)
- [x] User can view Privacy Policy (Link to https://gnosis-safe.io/privacy/)
- [x] User can view used licenses (Link to https://gnosis-safe.io/licenses/)
- [x] Terms, PP and licenses are not hardcoded, but links that open a browser window (exactly how we do it in the current app)
- [x] User can get in touch with us (Email, Discord, Twitter)
  - [x] As a company we decided to moved to Discord, so let's take this opportunity.
  - [x] Help center: https://help.gnosis-safe.io
  - [x] Email: safe@gnosis.io
  - [x] Discord: https://discord.gg/FPMRAwK
  - [x] Twitter: https://twitter.com/gnosisSafe
  - [x] Feature suggestion: https://safe.cnflx.io/
- [x] User can see other app settings:
  - [x] ENS resolver address
  - [x] RPC endpoint url
  - [x] Backend services urls (safe-relay, safe-tranasction)
  - [x] Tap to copy urls
